---
resources:
- name: airfix
  type: git
  webhook_token: ((webhook_token))
  source:
    ignore_paths: [version, README.md]
    <<: &git_source
      uri: git@github.com:EngineerBetter/airfix.git
      private_key: |
        ((github_private_key))
      branch: main
- name: version
  type: semver
  source:
    driver: git
    branch: main
    file: version
    depth: 1
    <<: *git_source
- name: release
  type: github-release
  source:
    owner: EngineerBetter
    repository: airfix
    access_token: ((github_access_token))

jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: airfix
    trigger: true
  - set_pipeline: self
    file: airfix/ci/pipeline.yml

- name: test
  serial: true
  plan:
  - get: airfix
    passed: [set-pipeline]
    trigger: true
  - task: test
    config:
      <<: &task-config
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: engineerbetter/pcf-ops }
        inputs:
        - name: airfix
      run:
        path: bash
        args:
        - -xeuc
        - |
          curl -L https://github.com/EngineerBetter/ironbird/releases/download/0.0.6/ironbird-linux -o /usr/local/bin/ironbird
          chmod +x /usr/local/bin/ironbird

          fly login -t eb -c https://ci.engineerbetter.com -u admin -p ((concourse_password))
          fly -t eb sync

          cd airfix

          pushd git-commit-if-changed
            ironbird --specs task_spec.yml --target eb
          popd

- name: release
  serial: true
  plan:
  - get: airfix
    passed: [test]
    trigger: true
  - put: version
    params:
      bump: patch
  - put: release
    params:
      name: built/name
      tag: version/version
